/* tslint:disable */
/* eslint-disable */
/**
 * Trackr
 * The Trackr API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTrackDto
 */
export interface UpdateTrackDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTrackDto
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTrackDto
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrackDto
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrackDto
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrackDto
     */
    duration?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrackDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrackDto
     */
    authorId?: string;
}

/**
 * Check if a given object implements the UpdateTrackDto interface.
 */
export function instanceOfUpdateTrackDto(value: object): value is UpdateTrackDto {
    return true;
}

export function UpdateTrackDtoFromJSON(json: any): UpdateTrackDto {
    return UpdateTrackDtoFromJSONTyped(json, false);
}

export function UpdateTrackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTrackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'description': json['description'] == null ? undefined : json['description'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
    };
}

export function UpdateTrackDtoToJSON(json: any): UpdateTrackDto {
    return UpdateTrackDtoToJSONTyped(json, false);
}

export function UpdateTrackDtoToJSONTyped(value?: UpdateTrackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'duration': value['duration'],
        'description': value['description'],
        'authorId': value['authorId'],
    };
}

